const StateCategory = [
    {id : 1, label : 'Abia', value : 'Abia'}, 
    {id : 2, label : 'Abuja', value : 'Abuja'}, 
    {id : 3, label : 'Adamawa', value : 'Adamawa'},  
    {id : 4, label : 'Akwa Ibom', value : 'Akwa Ibom'},  
    {id : 5, label : 'Anambra', value : 'Anambra'},  
    {id : 6, label : 'Bauchi', value : 'Bauchi'},  
    {id : 7, label : 'Bayelsa', value : 'Bayelsa'},  
    {id : 8, label : 'Benue', value : 'Benue'},  
    {id : 9, label : 'Borno', value : 'Borno'},  
    {id : 10, label : 'Cross River', value : 'Cross River'},  
    {id : 11, label : 'Delta', value : 'Delta'},  
    {id : 12, label : 'Ebonyi', value : 'Ebonyi'},  
    {id : 13, label : 'Edo', value : 'Edo'},  
    {id : 14, label : 'Ekiti', value : 'Ekiti'},  
    {id : 15, label : 'Enugu', value : 'Enugu'},     
    {id : 14, label : 'Gombe', value : 'Gombe'},  
    {id : 17, label : 'Imo', value : 'Imo'},  
    {id : 18, label : 'Jigawa', value : 'Jigawa'},  
    {id : 19, label : 'Kaduna', value : 'Kaduna'},  
    {id : 20, label : 'Kano', value : 'Kano'},  
    {id : 21, label : 'Katsina', value : 'Katsina'},  
    {id : 22, label : 'Kebbi', value : 'Kebbi'},  
    {id : 23, label : 'Kogi', value : 'Kogi'},  
    {id : 24, label : 'Kwara', value : 'Kwara'},  
    {id : 25, label : 'Lagos', value : 'Lagos'},  
    {id : 26, label : 'Nasarawa', value : 'Nasarawa'},  
    {id : 27, label : 'Niger', value : 'Niger'},  
    {id : 28, label : 'Ogun', value : 'Ogun'},  
    {id : 29, label : 'Ondo', value : 'Ondo'},  
    {id : 30, label : 'Osun', value : 'Osun'},  
    {id : 31, label : 'Oyo', value : 'Oyo'},  
    {id : 32, label : 'Plateau', value : 'Plateau'},  
    {id : 33, label : 'Rivers', value : 'Rivers'},  
    {id : 34, label : 'Sokoto', value : 'Sokoto'},  
    {id : 35, label : 'Taraba', value : 'Taraba'},  
    {id : 36, label : 'Yobe', value : 'Yobe'},  
    {id : 37, label : 'Zamfara', value : 'Zamfara'},  
   
]

export default StateCategory;

